networks:
  comm_net:
    external: true
    name: comm_net

services:
  mermaid-local:
    image: markdown-notes-app:latest
    build:
      context: https://github.com/testbenchcc/markdown-notes-app.git
      dockerfile: Dockerfile
    container_name: markdown-notes-app
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - comm_net