networks:
  comm_net:
    external: true
    name: comm_net

services:
  markdown-notes-app:
    image: markdown-notes-app:latest
    build:
      context: https://github.com/testbenchcc/markdown-notes-app.git
      dockerfile: Dockerfile
    container_name: markdown-notes-app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - comm_net