networks:
  comm_net:
    external: true
    name: comm_net

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: markdown-notes-app:latest
    container_name: markdown-notes-app
    ports:
      - "3002:8000"
    volumes:
      - .:/app
      - /home/tbrinkhuis/.ssh:/root/.ssh:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - comm_net